### PR TITLE
Additional autorest cli and dotnet build cli input 

### PR DESCRIPTION
**Pull request by fredrik-hellmangroup**
- Added support to generate autorest based on local swagger.json instead of URL
- Additional autorest CLI switches
- Ability to skip dotnet build if wanted
- Added support for dotnet build cli switches

### CODE REVIEW

**Comment by fredrik-hellmangroup** [comment]
@VaclavK @williamoconnorme could you please have a look at this pr?

**Comment by VaclavK** [comment]
@surfaace i am no longer with eSW 

@dguerin @cjfarrelly fyi

**Review by tabman83 — COMMENTED** [review]
Hi there, can you tell what is the use case for these changes?

**Comment by fredrik-hellmangroup** [comment]
@tabman83 the use case is that in our company we do already use powershell script to do the changes suggested and instead of maintaining and moving this script around I would like to reuse the marketplace build task you created. For a cleaner and easier to maintain solution.

Also to increase the flexibility in naming you autorest client so it doesn't just take the swagger name.
In addition having a local swagger file as input allowed you to generate autorest in build pipeline instead of publishing the API and getting it from there

**Comment by fredrik-hellmangroup** [comment]
Basically just increase flexibility of the already existing marketplace tool instead of forking it

**Comment by fredrik-hellmangroup** [comment]
@tabman83 any status?

**Review by tabman83 — APPROVED** [review]

**Pull request merged**
